version: '3.8'



services:
  teamspeak:
    image: teamspeak
    restart: always
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: db
      TS3SERVER_DB_USER: root
      TS3SERVER_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
    labels:
      - "traefik.enable=true"
      - "traefik.port=10011"
      - "traefik.http.routers.teamspeak.rule=Host(`${TEAMSPEAK_DOMAIN}`)"
      - "traefik.http.routers.teamspeak.entrypoints=websecure"
      - "traefik.http.routers.teamspeak.tls.certresolver=${TLS_RESOLVER}"
    volumes:
      - teamspeak:/var/ts3server/



  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: teamspeak
    volumes:
      - teamspeak-db:/var/lib/mysql/



volumes:
  teamspeak:
  teamspeak-db: